replicaCount: 1

image:
  repository: ghcr.io/bh-devops-playground/microservice-a
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30202

resources:
  requests:
    cpu: "250m"
    memory: "50Mi"
  limits:
    cpu: "0.5"
    memory: "512Mi"
