name: Helm Chart Release

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    conclusions:
      - success

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set Helm Chart Version
        id: set_version
        run: |
          git fetch --tags  # Ensure tags exist
          TAG=$(git describe --tags --abbrev=0 || echo "0.0.0-dev")  # Fallback if no tag exists
          echo "CHART_VERSION=$TAG" >> $GITHUB_ENV

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          helm package helm --version ${{ env.CHART_VERSION }} --app-version ${{ env.CHART_VERSION }}
          mv ./microservice-a-${{ env.CHART_VERSION }}.tgz ./helm-chart-${{ env.CHART_VERSION }}.tgz

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Helm Chart to GHCR
        run: |
          helm push helm-chart-${{ env.CHART_VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}
